---
title: "AMSA 105013: System Administration"
tbl-colwidths: [5,5,5,30,5,5,5,5,5,30]
format:
    html:
        toc: false
---

## Planificaci贸

A continuaci贸 es presenta un calendari complet dels temes, el contingut del curs i les tasques per al semestre. Tingueu en compte que aquest calendari 茅s un document viu i es pot actualitzar. Tots els canvis es publicaran aqu铆 per assegurar-vos que teniu la informaci贸 m茅s actual.

::: column-screen-inset-right
| Setmana | Tipus              | Data       | Tema                                                     | Diapositives | Apunts | Laboratori | Altres | Tasques | Lliuraments  |                                                                                                                                       |
|:----:|:------------------:|:----------:|:---------------------------------------------------------|:--:|:--:|:--:|:--:|:--:|:----------------------------------------------------------------------------------------------------------------------------------------:|
| 1    | Teoria             |10/09/25    | **Unitat 01**: Fonaments de lAdministraci贸 de Sistemes  | [](../slides/01-foundations-of-systems-administration.html#prepare){aria-label="Fonaments de lAdministraci贸 de Sistemes "}  |    |  |  |  [](../exercises/01-foundations-of-systems-administration/01-ex-week1.html#prepare) [](../exercises/01-foundations-of-systems-administration/02-ex-week1.html#prepare)      |                                                                                                                                          |
| 2 | Laboratori |15/09/25 | **Unitat 01**: Fonaments de lAdministraci贸 de Sistemes  |  |    | [И](/laboratories/01-foundations/01-aws-introduction.html#prepare) [И](/laboratories/01-foundations/02-aws-wordpress.html#prepare) |  |  |  |                                                                                                                                       |
| 2    | Teoria             |17/09/25    | **Unitat 02**: Arrencada del sistema                      | [](../slides/02-booting.html#prepare){aria-label="Arrencada del sistema "}  |    |  |  |  [](../exercises/02-booting/01-ex-week2.html#prepare) [](../exercises/02-booting/02-ex-week2.html#prepare) [](../exercises/02-booting/03-ex-week2.html#prepare)      |                                                                                                                                          |
| 3 | Laboratori |24/09/25 | **Unitat 02**: Arrencada del sistema (II) | [](../slides/02-booting-part2.html#prepare){aria-label="Arrencada del sistema "}  |    |  | [](https://github.com/amsa-gei-udl-2526-105013/course/issues/3) | [](../exercises/02-booting/04-ex-week3.html#prepare) [](../exercises/02-booting/05-ex-week3.html#prepare)     |   
| 4    | Teoria             |29/09/25    | **Unitat 02**: Arrencada del sistema (III)       | [](../slides/02-booting-part3.html#prepare)  |   |  | [](https://github.com/amsa-gei-udl-2526-105013/course/issues/3)  |    [](../exercises/02-booting/06-ex-week4.html#prepare) [](../exercises/02-booting/07-ex-week4.html#prepare)  |       [烩](../projects/01-project/01-project.html#prepare) |    
| 4 | Laboratori |01/10/25 | **Networking**  |   |    | [И](/laboratories/02-network/01-aws-wordpress.html#prepare) |
| 5    | Teoria             |06/10/25    | **Unitat 03**: Sistemes de fitxers (Part 1)            | [](../slides/03-filesystem-part1.html#prepare){aria-label="Sistemes de fitxers (Part 1) "}  |    |  |  | [](../exercises/03-fs/08-ex-week5.qmd) 
| 5 | Laboratori |08/10/25 | **Networking**  |   |    | [И](/laboratories/02-network/01-aws-wordpress.html#prepare) |
| 6    | Teoria             |13/10/25    | **Unitat 03**: Sistemes de fitxers (Part 2)            | [](../slides/03-filesystem-part2.html#prepare){aria-label="Sistemes de fitxers (Part 2) "}  |    |  |  | [](../exercises/03-fs/09-ex-week6.qmd) 
| 6 | Laboratori |15/10/25 | (Vaga general)  |   |    | |
| 7   | Teoria             |20/10/25    | **Unitat 03**: Sistemes de fitxers (Part 3)            | [](../slides/03-filesystem-part3.html#prepare){aria-label="Sistemes de fitxers (Part 3) "}  |    |  |  | [](../exercises/03-fs/10-ex-week7.qmd) || 
| 7 | Laboratori | 22/10/25 | **Unitat 03: Prctica 02**  |  | | || |[烩](../projects/02-project/02-project.html#prepare) |